//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Xaml.Behaviors.DesignTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Xaml.Behaviors.Design.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string Category_Animation_Properties {
            get {
                return ResourceManager.GetString("Category_Animation_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Category_Common_Properties {
            get {
                return ResourceManager.GetString("Category_Common_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Category_Tag_Properties {
            get {
                return ResourceManager.GetString("Category_Tag_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls a method on a specified object when invoked..
        /// </summary>
        internal static string Description_CallMethodAction {
            get {
                return ResourceManager.GetString("Description_CallMethodAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or sets the name of the method to invoke..
        /// </summary>
        internal static string Description_CallMethodAction_MethodName {
            get {
                return ResourceManager.GetString("Description_CallMethodAction_MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the object that exposes the method..
        /// </summary>
        internal static string Description_CallMethodAction_TargetObject {
            get {
                return ResourceManager.GetString("Description_CallMethodAction_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will change a specified property to a specified value when invoked..
        /// </summary>
        internal static string Description_ChangePropertyAction {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the number of seconds the property change will take to complete..
        /// </summary>
        internal static string Description_ChangePropertyAction_Duration {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the EasingFunction to use with the animation when the ChangePropertyAction is invoked..
        /// </summary>
        internal static string Description_ChangePropertyAction_Ease {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_Ease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether the value should be added to the current PropertyValue. If it cannot be added, it will replace it..
        /// </summary>
        internal static string Description_ChangePropertyAction_Increment {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the property to change..
        /// </summary>
        internal static string Description_ChangePropertyAction_PropertyName {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the object whose property will be changed..
        /// </summary>
        internal static string Description_ChangePropertyAction_TargetObject {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the value to set..
        /// </summary>
        internal static string Description_ChangePropertyAction_Value {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will change the state of the specified Storyboard when executed..
        /// </summary>
        internal static string Description_ControlStoryboardAction {
            get {
                return ResourceManager.GetString("Description_ControlStoryboardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the action to execute on the Storyboard..
        /// </summary>
        internal static string Description_ControlStoryboardAction_ControlStoryboardOption {
            get {
                return ResourceManager.GetString("Description_ControlStoryboardAction_ControlStoryboardOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the targeted Storyboard..
        /// </summary>
        internal static string Description_ControlStoryboardAction_Storyboard {
            get {
                return ResourceManager.GetString("Description_ControlStoryboardAction_Storyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles between two states based on a conditional statement..
        /// </summary>
        internal static string Description_DataStateBehavior {
            get {
                return ResourceManager.GetString("Description_DataStateBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the binding that produces the property value of the data object..
        /// </summary>
        internal static string Description_DataStateBehavior_Binding {
            get {
                return ResourceManager.GetString("Description_DataStateBehavior_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the visual state to transition to when the condition is not met..
        /// </summary>
        internal static string Description_DataStateBehavior_FalseState {
            get {
                return ResourceManager.GetString("Description_DataStateBehavior_FalseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the visual state to transition to when the condition is met..
        /// </summary>
        internal static string Description_DataStateBehavior_TrueState {
            get {
                return ResourceManager.GetString("Description_DataStateBehavior_TrueState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the value to be compared with the property value of the data object..
        /// </summary>
        internal static string Description_DataStateBehavior_Value {
            get {
                return ResourceManager.GetString("Description_DataStateBehavior_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the source object for this EventTriggerBase. If the name is not set or cannot be resolved, AssociatedObject will be used..
        /// </summary>
        internal static string Description_EventTriggerBase_SourceName {
            get {
                return ResourceManager.GetString("Description_EventTriggerBase_SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the source object for this EventTriggerBase. If the source object is not set, the SourceName property will be used instead. If SourceName is not set or cannot be resolved, AssociatedObject will be used..
        /// </summary>
        internal static string Description_EventTriggerBase_SourceObject {
            get {
                return ResourceManager.GetString("Description_EventTriggerBase_SourceObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A behavior that listens for a specified event on its source and executes its actions when that event is fired..
        /// </summary>
        internal static string Description_EventTriggerBehavior {
            get {
                return ResourceManager.GetString("Description_EventTriggerBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the event to listen for..
        /// </summary>
        internal static string Description_EventTriggerBehavior_EventName {
            get {
                return ResourceManager.GetString("Description_EventTriggerBehavior_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animates changes to the layout properties of objects inside a panel..
        /// </summary>
        internal static string Description_FluidMoveBehavior {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether this Behavior will affect only the specified object or its children..
        /// </summary>
        internal static string Description_FluidMoveBehavior_AppliesTo {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_AppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the number of seconds the transition will take to complete..
        /// </summary>
        internal static string Description_FluidMoveBehavior_Duration {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the EasingFunction to use for the horizontal component of the move..
        /// </summary>
        internal static string Description_FluidMoveBehavior_EaseX {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_EaseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the EasingFunction to use for the vertical component of the move..
        /// </summary>
        internal static string Description_FluidMoveBehavior_EaseY {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_EaseY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the value that indicates whether elements are allowed to float above their current container when changing to another container..
        /// </summary>
        internal static string Description_FluidMoveBehavior_FloatAbove {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_FloatAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the tag whose associated values will be read from the data stored by the FluidMoveSetTagBehavior..
        /// </summary>
        internal static string Description_FluidMoveBehavior_InitialTag {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_InitialTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the extra path needed to navigate and access the data that gets read from the stored values returned by the FluidMoveSetTagBehavior..
        /// </summary>
        internal static string Description_FluidMoveBehavior_InitialTagPath {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_InitialTagPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether the Behavior is currently active..
        /// </summary>
        internal static string Description_FluidMoveBehavior_IsActive {
            get {
                return ResourceManager.GetString("Description_FluidMoveBehavior_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the tag whose associated values will be stored and consumed by the FluidMoveBehavior..
        /// </summary>
        internal static string Description_FluidMoveSetTagBehavior_Tag {
            get {
                return ResourceManager.GetString("Description_FluidMoveSetTagBehavior_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the extra path needed to navigate and access the data consumed by the FluidMoveBehavior..
        /// </summary>
        internal static string Description_FluidMoveSetTagBehavior_TagPath {
            get {
                return ResourceManager.GetString("Description_FluidMoveSetTagBehavior_TagPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will transition a FrameworkElement to a specified VisualState when executed..
        /// </summary>
        internal static string Description_GoToStateAction {
            get {
                return ResourceManager.GetString("Description_GoToStateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the VisualState..
        /// </summary>
        internal static string Description_GoToStateAction_StateName {
            get {
                return ResourceManager.GetString("Description_GoToStateAction_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the target object..
        /// </summary>
        internal static string Description_GoToStateAction_TargetObject {
            get {
                return ResourceManager.GetString("Description_GoToStateAction_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets whether or not to use a VisualTransition to transition between states..
        /// </summary>
        internal static string Description_GoToStateAction_UseTransitions {
            get {
                return ResourceManager.GetString("Description_GoToStateAction_UseTransitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes a specified ICommand when invoked..
        /// </summary>
        internal static string Description_InvokeCommandAction {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the command the action should invoke..
        /// </summary>
        internal static string Description_InvokeCommandAction_Command {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the ICommand to invoke..
        /// </summary>
        internal static string Description_InvokeCommandAction_CommandName {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the parameter that is passed to ICommand.Execute. If this is not set, the parameter from the InvokeCommandAction.Execute method will be used..
        /// </summary>
        internal static string Description_InvokeCommandAction_CommandParameter {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_CommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the converter that is run on the parameter of the InvokeCommandAction.Execute method..
        /// </summary>
        internal static string Description_InvokeCommandAction_InputConverter {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_InputConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the language that is passed to the IValueConverter.Convert method of InputConverter..
        /// </summary>
        internal static string Description_InvokeCommandAction_InputConverterLanguage {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_InputConverterLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the parameter that is passed to the IValueConverter.Convert method of InputConverter..
        /// </summary>
        internal static string Description_InvokeCommandAction_InputConverterParameter {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_InputConverterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a file or URL destination..
        /// </summary>
        internal static string Description_LaunchURLOrFileAction {
            get {
                return ResourceManager.GetString("Description_LaunchURLOrFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the path of the file or web page to open..
        /// </summary>
        internal static string Description_LaunchURLOrFileAction_Path {
            get {
                return ResourceManager.GetString("Description_LaunchURLOrFileAction_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositions an object when the user drags it..
        /// </summary>
        internal static string Description_MouseDragElementBehavior {
            get {
                return ResourceManager.GetString("Description_MouseDragElementBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether the movement of the dragged object is limited by the bounds of the parent object..
        /// </summary>
        internal static string Description_MouseDragElementBehavior_ConstrainToParentBounds {
            get {
                return ResourceManager.GetString("Description_MouseDragElementBehavior_ConstrainToParentBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the X position of the dragged object, relative to the left edge of the root object..
        /// </summary>
        internal static string Description_MouseDragElementBehavior_X {
            get {
                return ResourceManager.GetString("Description_MouseDragElementBehavior_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Y position of the dragged object, relative to the top edge of the root object..
        /// </summary>
        internal static string Description_MouseDragElementBehavior_Y {
            get {
                return ResourceManager.GetString("Description_MouseDragElementBehavior_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will play a sound to completion..
        /// </summary>
        internal static string Description_PlaySoundAction {
            get {
                return ResourceManager.GetString("Description_PlaySoundAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the location of the sound file..
        /// </summary>
        internal static string Description_PlaySoundAction_Source {
            get {
                return ResourceManager.GetString("Description_PlaySoundAction_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or set the volume of the sound..
        /// </summary>
        internal static string Description_PlaySoundAction_Volume {
            get {
                return ResourceManager.GetString("Description_PlaySoundAction_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the object that this action will affect..
        /// </summary>
        internal static string Description_TargetedTriggerAction_TargetName {
            get {
                return ResourceManager.GetString("Description_TargetedTriggerAction_TargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the object that this action will affect..
        /// </summary>
        internal static string Description_TargetedTriggerAction_TargetObject {
            get {
                return ResourceManager.GetString("Description_TargetedTriggerAction_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the user to use common touch gestures to translate, zoom, and rotate the attached object..
        /// </summary>
        internal static string Description_TranslateZoomRotateBehavior {
            get {
                return ResourceManager.GetString("Description_TranslateZoomRotateBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the value indicating whether the zoom and translate position of the attached object is limited by the bounds of the parent object..
        /// </summary>
        internal static string Description_TranslateZoomRotateBehavior_ConstrainToParentBounds {
            get {
                return ResourceManager.GetString("Description_TranslateZoomRotateBehavior_ConstrainToParentBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a number indicating the maximum zoom value allowed..
        /// </summary>
        internal static string Description_TranslateZoomRotateBehavior_MaximumScale {
            get {
                return ResourceManager.GetString("Description_TranslateZoomRotateBehavior_MaximumScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a number indicating the minimum zoom value allowed..
        /// </summary>
        internal static string Description_TranslateZoomRotateBehavior_MinimumScale {
            get {
                return ResourceManager.GetString("Description_TranslateZoomRotateBehavior_MinimumScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a number describing the rate at which the rotation will decrease..
        /// </summary>
        internal static string Description_TranslateZoomRotateBehavior_RotationalFriction {
            get {
                return ResourceManager.GetString("Description_TranslateZoomRotateBehavior_RotationalFriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value specifying which zooming and translation variants to support..
        /// </summary>
        internal static string Description_TranslateZoomRotateBehavior_SupportedGestures {
            get {
                return ResourceManager.GetString("Description_TranslateZoomRotateBehavior_SupportedGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a number describing the rate at which the translation will decrease..
        /// </summary>
        internal static string Description_TranslateZoomRotateBehavior_TranslateFriction {
            get {
                return ResourceManager.GetString("Description_TranslateZoomRotateBehavior_TranslateFriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether this Action is active..
        /// </summary>
        internal static string Description_TriggerAction_IsEnabled {
            get {
                return ResourceManager.GetString("Description_TriggerAction_IsEnabled", resourceCulture);
            }
        }
    }
}
